- name: Stop judge
  systemd: 
    name: nasajudgeapi
    state: stoped
  become: true
  ignore_errors: true

- name: Init os var
  include_vars: "vars/{{ ansible_system | lower }}.yml"

- name: Change mode of wireguard dir
  file:
    path: "{{ wireguarddir }}"
    mode: "0711"
  become: true
  delegate_to: "{{ wireguard.host }}"

- name: Generate VPN server
  import_tasks: setvpn.yml
  delegate_to: "{{ wireguard.host }}"
  notify: Start wireguard VPN

- name: Set bind9 options
  import_tasks: setnamed.yml
  delegate_to: "{{ nameserver.host }}"
  notify: Restart named

- name: Add nasa user
  user:
    name: nasa
    generate_ssh_key: yes
  become: true

- name: Slurp authorized_key of nasa
  slurp:
    src: "/home/nasa/.ssh/id_rsa.pub"
  register: authorized_key

- name: Add nasa user on wireguard host
  user:
    name: nasa
  become: true
  delegate_to: "{{ wireguard.host }}"

- name: Set authorized_key of nasa user on wireguard host
  ansible.posix.authorized_key:
    user: nasa
    key: "{{ authorized_key['content'] | b64decode }}"
  become: true
  delegate_to: "{{ wireguard.host }}"

- name: Set nasa sudo nopass on wireguard host
  copy:
    content: "nasa ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/nasa"
  become: true
  delegate_to: "{{ wireguard.host }}"

- name: Add nasa user on nameserver host
  user:
    name: nasa
  become: true
  delegate_to: "{{ nameserver.host }}"

- name: Set authorized_key of nasa user on nameserver host
  ansible.posix.authorized_key:
    user: nasa
    key: "{{ authorized_key['content'] | b64decode }}"
  become: true
  delegate_to: "{{ nameserver.host }}"

- name: Set nasa sudo nopass on nameserver host
  copy:
    content: "nasa ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/nasa"
  become: true
  delegate_to: "{{ nameserver.host }}"

- name: Copy judge api directory
  copy:
    src: "src/"
    dest: "{{ nasajudgeapidir }}/"
    owner: nasa
    group: nasa
  become: true

- name: Check config files exist
  stat:
    path: "{{ nasajudgeapidir }}/{{ item }}"
  become: true
  register: config
  with_items:
    - config.yaml

- name: Copy config files
  template:
    src: "templates/config/{{ item.item }}"
    dest: "{{ nasajudgeapidir }}/{{ item.item }}"
    owner: nasa
    group: nasa
  become: true
  when: not item.stat.exists
  with_items: "{{ config.results }}"

- name: Copy executable file
  template:
    src: "templates/bin/nasajudgeapi"
    dest: "/usr/local/bin/nasajudgeapi"
    mode: 0755
  become: true

- name: Copy systemd
  template:
    src: "templates/systemd/nasajudgeapi.service"
    dest: "{{ etc }}/systemd/system/nasajudgeapi.service"
  become: true

- name: Run venv init
  script: "script/initvenv.sh {{ nasajudgeapidir }}"
  become: true
  become_user: nasa
  notify: Start judge
