- name: Set bind9 options
  include_role:
    name: Bind9Manager/roles/setoption
  vars:
    option: "{{ item.option }}"
    regexp: "{{ item.regexp }}"
  with_items:
    - option: "    allow-new-zones yes;"
      regexp: "^((?!(.|\r|\n)*).)*$"
    - option: "    allow-query { any; };"
      regexp: "^((?!(.|\r|\n)*).)*$"
    - option: "    max-ncache-ttl 0;"
      regexp: "^((?!(.|\r|\n)*).)*$"
    - option: "    max-cache-ttl 0;"
      regexp: "^((?!(.|\r|\n)*).)*$"
    - option: "    dnssec-validation no;"
      regexp: "^\\s*dnssec-validation\\s*.*;\\s*$"
