enablessl: false
ListenHost: "{{ ListenHost }}"
ListenPort: {{ ListenPort }}
certificate: ""
privatekey: ""
judegbackendhost: "127.0.0.1"
{{ { "nameserver":nameserver } | to_nice_yaml(indent=2, sort_keys=False) }}
{{ { "wireguard":wireguard } | to_nice_yaml(indent=2, sort_keys=False) }}
workerspubkeys: []
workers: []

