- name: Gen data with netmask
  ansible.utils.update_fact:
    updates:
    - path: record.data
      value: "{{ record.netmask | ansible.utils.nthhost(ipindex) }}"
  register: updated
  when: "'data' not in record and 'netmask' in record"

- name: Set record with netmask
  set_fact:
    nowrecord: "{{ updated.record }}"
  when: "'data' not in record and 'netmask' in record"

- name: Set record
  set_fact:
    nowrecord: "{{ record }}"
  when: "'data' in record"

- name: Set data
  set_fact:
    newusername: "{{ username }}"

- name: Set data
  set_fact:
    username: "{{ oldusername }}"

- block:
  - name: Delete DNS record
    import_role:
      name: Bind9Manager/roles/delrecord
    vars:
      host: "{{ nowrecord.host }}"
      zone: "{{ nowrecord.zone }}"
    delegate_to: "{{ nameserver.host }}"
  rescue:
  - debug:
      msg: "error"

- name: Set data
  set_fact:
    username: "{{ newusername }}"

- block:
  - name: Set DNS record
    import_role:
      name: Bind9Manager/roles/addrecord
    vars:
      host: "{{ nowrecord.host }}"
      zone: "{{ nowrecord.zone }}"
      type: "{{ nowrecord.type }}"
      data: "{{ nowrecord.data }}"
      NSIP: "{{ nowrecord.NSIP }}"
    delegate_to: "{{ nameserver.host }}"
  rescue:
  - debug:
      msg: "error"
