- block:
  - name: Copy VPN file
    copy: 
      remote_src: true 
      src: "/etc/wireguard/{{ tunnel.client.dir }}/{{ oldusername }}.conf"
      dest: "/etc/wireguard/{{ tunnel.client.dir }}/{{ username }}.conf"
    become: true
    delegate_to: "{{ wireguard.host }}"

  - name: Remove old VPN file
    file: 
      path: "/etc/wireguard/{{ tunnel.client.dir }}/{{ oldusername }}.conf"
      state: absent
    become: true
    delegate_to: "{{ wireguard.host }}"

  - name: Change VPN config
    lineinfile:
      path: "/etc/wireguard/{{ tunnel.name }}.conf"
      regexp: "^# BEGIN {{ oldusername }}$"
      line: "# BEGIN {{ username }}"
    become: true
    delegate_to: "{{ wireguard.host }}"
  
  - name: Change VPN config
    lineinfile:
      path: "/etc/wireguard/{{ tunnel.name }}.conf"
      regexp: "^# END {{ oldusername }}$"
      line: "# END {{ username }}"
    become: true
    delegate_to: "{{ wireguard.host }}"

  - name: Reload VPN
    shell: "bash -c \"wg syncconf {{ tunnel.name }} <(wg-quick strip {{ tunnel.name }})\""
    become: true
    ignore_errors: yes
    delegate_to: "{{ wireguard.host }}"

  rescue:
  - debug:
      msg: "error"

