- block:
  - name: Generate VPN server
    import_role:
      name: VpnGenerator/roles/addwguser
    vars:
      servername: "{{ tunnel.name }}"
      username: "{{ username }}"
      addresses: "{{ tunnel.server.ips | ipaddr('subnet') | map('nthhost', ipindex) | join(',') }}"
      fqdn: "{{ tunnel.client.fqdn }}"
      routes: "{{ tunnel.client.AllowedIPs }}"
      clientconfigdir: "{{ tunnel.client.dir }}"
      nameserver: "{{ tunnel.client.DNS }}"
      moreconfig: "{{ tunnel.client.moreconfig }}"
    delegate_to: "{{ wireguard.host }}"
  rescue:
  - debug:
      msg: "user exist"

