- hosts: localhost
  roles: []
  
  tasks:
    - name: Set worker
      add_host:
        name: "{{ workerhost }}"
        groups: workers
        ansible_ssh_user: "{{ workeruser }}"
      changed_when: false
  
  handlers: []

- hosts: workers
  roles: []

  tasks:
    - name: include main task
      include: "{{ missionpath }}"

  handlers: []
