- hosts: localhost
  vars_files: 
    - defaults/main.yml
  
  roles: []
  
  tasks:
    - name: Set lab vars
      include_vars: "labs/{{ labId }}/config.yaml"

    - name: Check is on host
      set_fact:
        workerhost: localhost
      when: checkonhost

    - name: Set worker
      add_host:
        name: "{{ workerhost }}"
        groups: workers
      when: not workerusedocker
    
    - name: Set worker(docker)
      add_host:
        name: "{{ workerhost }}"
        groups: workers
        ansible_connection: docker
        ansible_ssh_user: "root"
        ansible_become_user: "root"
        ansible_become: "yes"
      when: workerusedocker
  
  handlers: []



- hosts: workers
  vars_files:
    - defaults/main.yml

  roles: []

  tasks:
    - name: include main task
      include: tasks/main.yml

  handlers:
    - include: handlers/main.yml
