- hosts: localhost
  vars_files: 
    - defaults/main.yml
  
  roles: []
  
  tasks:
    - name: Set lab vars
      include_vars: "labs/{{ labId }}/config.yaml"

    - name: Check is on host
      set_fact:
        workerhost: localhost
      when: checkonhost

    - name: Set worker
      add_host:
        name: "{{ workerhost }}"
        groups: workers
      changed_when: false
  
  handlers: []



- hosts: workers
  vars_files:
    - defaults/main.yml

  roles: []

  tasks:
    - name: include main task
      include: tasks/main.yml

  handlers:
    - include: handlers/main.yml
