- name: "Check named.conf.options exists"
  stat:
    path: "{{ nameddir }}/named.conf.options"
  register: result

- name: "Set options path"
  set_fact:
    namedoptions: "{{ nameddir }}/named.conf.options"
  when: result.stat.exists

- name: "Get named.conf zone file path"
  set_fact:
    namedoptions: "{{ nameddir }}/named.conf"
  when: not result.stat.exists

- name: "Set zonepath var"
  set_fact:
    zonepath: "{{ lookup('file', namedoptions) | regex_search('\\s*directory\\s*\"(.*)\";', '\\1') | first }}"
