- name: "Generate result list"
  set_fact: 
    result: "{{ result | default({}) | combine({checklist.key:((result[checklist.key] | default([]))+[{}])}) }}"
  with_items: "{{ checklist.value }}"
  when: (checklist.key not in (result | default({}))) or (((result | default({}))[checklist.key] | length) < (checkpoints[checklist.key] | length))

- name: "Run checkgroup: {{ checklist.key }}"
  include_tasks: "checkpoint.yml"
  loop: "{{ checklist.value }}"
  loop_control:
    loop_var: taskindex
  when: (result[checklist.key][taskindex] | length) == 0

