- name: clear taskpath
  set_fact:
    taskpath: "../{{ clear.scriptname | default('clear') }}"

- name: Run clear (script)
  command: 
    cmd: "{{ clear.command }}"
    chdir: "/tmp/{{ taskId }}/workspace"
  become: "{{ clear.become | default(false) }}"
  ignore_errors: true
  when: not ansiblejudgescript

- name: Run clear (ansible)
  include_tasks: "labs/{{ labId }}/clear.yml"
  when: ansiblejudgescript

- name: Remove script on worker
  file: 
    state: absent
    path: "/tmp/{{ taskId }}"
  ignore_errors: true
- name: Restore resolv.conf
  copy: 
    src: "/tmp/resolv.conf.bak"
    dest: "/etc/resolv.conf"
    remote_src: true
  become: true
  ignore_errors: true

- name: Remove /tmp/resolv.conf.bak
  file: 
    state: absent
    path: "/tmp/resolv.conf.bak"
  become: true
  ignore_errors: true
