- block:
  - name: "install {{ nowpackage }}"
    include_role:
      name: "package"
    vars:
      packagename: "{{ nowpackage }}"

  rescue:
  - name: Check resolv.conf bak
    stat:
      path: "/tmp/resolv.conf.bak"
    register: resolvconfig
    become: true

  - name: Restore resolv.conf
    copy: 
      src: "/tmp/resolv.conf.bak"
      dest: "/etc/resolv.conf"
      remote_src: true
    become: true
    when: resolvconfig.stat.exist

  - set_fact:
      retrytime: "{{ (retrytime | default(0) | int)+1 }}"
    when: (retrytime | default(0) | int) < 3

  - include_tasks: installpackage.yml
    when: (retrytime | default(0) | int) < 3

  always:
  - set_fact:
      retrytime: 0
