- block:
  - name: "install {{ nowpackage }}"
    include_role:
      name: "{{ nowpackage }}"
  rescue:
  - name: Restore resolv.conf
    copy: 
      src: "/tmp/resolv.conf.bak"
      dest: "/etc/resolv.conf"
      remote_src: true
    become: true
  - set_fact:
      retrytime: "{{ (retrytime | default(0) | int)+1 }}"
    when: (retrytime | default(0) | int) < 3
  - include_tasks: installpackage.yml
    when: (retrytime | default(0) | int) < 3

- set_fact:
    retrytime: 0
