- name: Set value var
  set_fact: "{{ nowdata.name }}={{ nowdata.data }}"
  when: nowdata.type == "input"

- name: Set file
  copy:
    content: "{{ nowdata.data | b64decode }}"
    dest: "/tmp/{{ taskId }}/workspace/{{ nowdata.name }}"
  when: nowdata.type == "upload"
